apiVersion: v1
kind: ConfigMap
metadata:
  name: feed-feeder
  labels:
    app: feed-feeder
    role: feed-feeder
  namespace: {{ .Release.Namespace }}
data:
  {{- template "feed-feeder.config_map_data" . }}

