# job to run database setup & migrations
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-feed-feeder-db
  labels:
    app: feed-feeder
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      {{- if .Values.feedFeeder.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.feedFeeder.nodeSelector | indent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1003
      restartPolicy: Never
      {{- if .Values.feedFeeder.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.feedFeeder.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-pg
          image: busybox:1.31
          securityContext:
            allowPrivilegeEscalation: false
          command: ['sh', '-c', 'until nc -z {{ .Values.feedFeeder.database.host }} {{ .Values.feedFeeder.database.port }} > /dev/null 2>&1 ; do echo "Postgres is unavailable - sleeping"; sleep 1; done']
      containers:
        - name: feed-feeder-setup-db
          image: "{{ .Values.feedFeeder.registry }}/{{ .Values.feedFeeder.image }}:{{ .Values.feedFeeder.tag }}"
          imagePullPolicy: {{ .Values.feedFeeder.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          command: [ "sh", "-c", "bin/rake db:setup || bin/rake db:migrate" ]
          envFrom:
            - configMapRef:
                name: feed-feeder-db-setup
            - secretRef:
                name: feed-feeder-db-setup
  backoffLimit: 4
