apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feed-feeder-ingress
  namespace: {{ .Release.Namespace }}
  {{- if .Values.feedFeeder.ingress.annotations }}
  annotations: {{ toYaml .Values.feedFeeder.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.feedFeeder.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.feedFeeder.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: feed-feeder
            port:
              number: 9292
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - {{ required "A valid hostname is required!" .Values.feedFeeder.ingress.hostname }}
      {{- if .Values.feedFeeder.ingress.certSecret }}
      secretName: {{ .Values.feedFeeder.ingress.certSecret }}
      {{- end }}
