apiVersion: v1
kind: Secret
metadata:
  name: feed-feeder
  labels:
    app: feed-feeder
    role: feed-feeder
  namespace: {{ .Release.Namespace }}
data:
  {{- template "feed-feeder.secret_data" . }}
