apiVersion: v1
kind: Secret
metadata:
  name: images-storage
  labels:
    app: feed-feeder
    role: images
  namespace: {{ .Release.Namespace }}
data:
  images_storage_creds.json: |-
    {{ .Values.feedFeeder.images.googleJsonKey | b64enc }}
