check_feeds:
  cron: "*/30 * * * *"
  class: FeedChecker
  args:
  queue: feed_checker
  description: "Checks all the feeds every 30 minutes and add new items"
send_items:
  cron: "*/30 * * * *"
  class: ItemsToApi
  args:
  queue: items_to_api
  description: "Check for items that need to be sent to the API and send them"
