name: Ruby

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: lateral
          POSTGRES_PASSWORD: lateral
          POSTGRES_DB: feed-feeder_development
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:alpine
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    strategy:
      matrix:
        ruby-version: [2.7.2]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: "Rails test"
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:setup --trace
          bundle exec rspec

  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || github.ref_type == 'tag' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build & push Feed Feeder
        run: |
          docker build -t ghcr.io/lateral/feed-feeder:${github.ref.name} -f deployment/docker/feed-feeder/Dockerfile .
          docker push ghcr.io/lateral/feed-feeder:${github.ref.name}
      - name: Docker build & push Images
        run: |
          docker build -t ghcr.io/lateral/images:${github.ref.name} -f deployment/docker/images/Dockerfile images/
          docker push ghcr.io/lateral/images:${github.ref.name}

  build-tmp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build & push Feed Feeder
        run: |
          docker build -t ghcr.io/lateral/feed-feeder:dev -f deployment/docker/feed-feeder/Dockerfile .
          docker push ghcr.io/lateral/feed-feeder:dev
      - name: Docker build & push Images
        run: |
          docker build -t ghcr.io/lateral/images:dev -f deployment/docker/images/Dockerfile images/
          docker push ghcr.io/lateral/images:dev
